name: 'Setup Godot'
description: 'Setup Godot for use in the workflow'

inputs:
  GODOT_VERSION:
    description: 'The godot version string'
    required: true
    type: string
  GODOT_REPO:
    description: 'The repository to download godot from'
    required: true
    type: string

outputs:
  GODOT_EXE:
    description: "The godot executable"
  GODOT_CONSOLE_EXE:
    description: "The godot executable for running in console mode"

runs:
  using: "composite"
  steps:
    cache_godot:
      name: "Setup Godot Cache"
      runs-on: "ubuntu-24.04"
      steps:
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: install python deps
          run: python -m pip install wget

        - name: setup godot
          run: python ./setup_godot.py --godot_repo "${{ inputs.GODOT_REPO }}" --godot_version "${{ inputs.GODOT_VERSION }}"
