name: 'Setup Headless Display Server'
description: 'Setup a headless display server for running gui programs in a headless environment'

runs:
  using: "composite"
  steps:

    - name: Install graphics drivers
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get -y install \
            libgl1-mesa-dri \
            mesa-utils \
            mesa-vulkan-drivers \
            libvulkan1 \
            vulkan-tools \
            mesa-vulkan-drivers \
            libvulkan1 \
            vulkan-tools \
            vulkan-validationlayers

    - uses: ./.github/actions/with_post_step
      if: runner.os != 'Windows'
      id: setup_godot
      with:
        main: bash ./.github/actions/setup_headless_display/xvfb_launch.sh
        post: bash ./.github/actions/setup_headless_display/xvfb_kill.sh