on:
  workflow_call:
    inputs:
      GODOT_VERSION:
        description: 'The godot version string'
        required: true
        type: string
      GODOT_REPO:
        description: 'The repository to download godot from'
        required: true
        type: string

jobs:
  export_game:
    strategy:
      fail-fast: false
      matrix:
        export_type:
          - macOS
          - "Windows (amd64)"
          - "Linux (amd64)"
          - "Linux (arm64)"
        include:
          - export_type: macOS
            os: macos-latest
            name: "macos"

          - export_type: "Windows (amd64)"
            os: windows-latest
            name: "windows"

          - export_type: "Linux (amd64)"
            os: ubuntu-24.04
            name: "linux_amd64"

          - export_type: "Linux (arm64)"
            os: ubuntu-24.04
            name: "linux_aarch64"

    name: "Export Game ${{ matrix.export_type }}"
    runs-on: ${{ matrix.os }}
    env:
      LIBGL_ALWAYS_SOFTWARE: true
      GALLIUM_DRIVER: llvmpipe
      DISPLAY: ":42"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: ./.github/actions/setup_godot
        id: setup_godot
        with:
          GODOT_VERSION: ${{ inputs.GODOT_VERSION }}
          GODOT_REPO: ${{ inputs.GODOT_REPO }}

      - name: Generate default_asset manifest files
        run: python default_assets/manifests.py

      - name: Retreive extensions artifacts
        uses: actions/download-artifact@v4
        with:
          name: extensions
          path: bin
      
      - name: install lavapipe
        if: runner.os == 'Linux'
        uses: serenity4/julia-lavapipe@v1
    
      - name: Setup display drivers (Linux and mac)
        if: runner.os != 'windows-latest'
        run: Xvfb :42 -screen 0 1280x720x24 &
      
      - name: Create the build directory
        run: mkdir build

      - name: Import all assets
        run: ${{ steps.setup_godot.outputs.GODOT_CONSOLE_EXE }} --headless --import project.godot

      - name: Export Client
        run: ${{ steps.setup_godot.outputs.GODOT_CONSOLE_EXE }} --headless --export-release 'Client ${{ matrix.export_type }}' project.godot

      - name: Export Server
        run: ${{ steps.setup_godot.outputs.GODOT_CONSOLE_EXE }} --headless --export-release 'Server ${{ matrix.export_type }}' project.godot

      - name: Tear down xvfb (Linux and Mac) 
        continue-on-error: true
        if: runner.os != 'windows-latest'
        run: killall Xvfb
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game_export_${{ matrix.name }}
          path: build

  combine_export_artifacts:
    name: "Combine Export Binaries"
    runs-on: "ubuntu-24.04"
    needs: export_game
    steps:
      - name: Download the export artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: game_export_*
          path: _build

      - name: properly place the export artifacts
        run: |
          mkdir -p build
          cp _build/*/* build

      - name: Publish extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game_exports
          path: build
