on:
  workflow_call:
    inputs:
      GODOT_VERSION:
        description: 'The godot version string'
        required: true
        type: string
      GODOT_REPO:
        description: 'The repository to download godot from'
        required: true
        type: string
      GAME_EXPORT_NAME:
        description: 'The name of the export'
        required: true
        type: string
      GAME_ARTIFACT_NAME:
        description: 'The name of the artifact to upload'
        required: true
        type: string
      EXTENSIONS_ARCHITECTURE:
        description: 'The architecture to build the extensions for'
        required: true
        type: string
      BUILD_OS:
        description: 'The OS to build the extension on'
        required: true
        type: string

jobs:
  export_game:
    name: "Export Game ${{ inputs.GAME_EXPORT_NAME }}"
    runs-on: ${{ inputs.BUILD_OS }}
    env:
      LIBGL_ALWAYS_SOFTWARE: true
      GALLIUM_DRIVER: llvmpipe
      MESA_VK_DEVICE_SELECT: llvmpipe
      DISPLAY: ":42"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: ./.github/actions/setup_godot
        id: setup_godot
        with:
          GODOT_VERSION: ${{ inputs.GODOT_VERSION }}
          GODOT_REPO: ${{ inputs.GODOT_REPO }}

      - uses: ./.github/actions/setup_headless_display

      - name: Generate default_asset manifest files
        run: python default_assets/manifests.py

      - name: Retreive extensions artifacts (debug)
        uses: actions/download-artifact@v4
        with:
          name: extension_${{ runner.os }}_debug_${{ inputs.EXTENSIONS_ARCHITECTURE }}
          path: bin

      - name: Retreive extensions artifacts (release)
        uses: actions/download-artifact@v4
        with:
          name: extension_${{ runner.os }}_release_${{ inputs.EXTENSIONS_ARCHITECTURE }}
          path: bin

      - name: install the editor extensions (debug)
        if: ${{ inputs.EXTENSIONS_ARCHITECTURE != 'native' }}
        uses: actions/download-artifact@v4
        with:
          name: extension_${{ runner.os }}_debug_native
          path: bin

      - name: install the editor extensions (release)
        if: ${{ inputs.EXTENSIONS_ARCHITECTURE != 'native' }}
        uses: actions/download-artifact@v4
        with:
          name: extension_${{ runner.os }}_release_native
          path: bin
      
      - name: Create the build directory
        run: mkdir build

      - name: Import all assets
        run: ${{ steps.setup_godot.outputs.GODOT_CONSOLE_EXE }} --import project.godot

      - name: Export Client
        run: ${{ steps.setup_godot.outputs.GODOT_CONSOLE_EXE }} --export-release 'Client ${{ inputs.GAME_EXPORT_NAME }}' project.godot

      - name: Export Server
        run: ${{ steps.setup_godot.outputs.GODOT_CONSOLE_EXE }} --export-release 'Server ${{ inputs.GAME_EXPORT_NAME }}' project.godot
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game_export_${{ inputs.GAME_ARTIFACT_NAME }}
          path: build